### ISSUE TITLE
Need for async version of NestedDiagnosticsContext => NestedDiagnosticsLogicalContext

### ISSUE THREAD

**Issue by 304NotModified** [NLog/NLog#1181]
Need for async variant of [`NestedDiagnosticsContext`](https://github.com/NLog/NLog/blob/master/src/NLog/NestedDiagnosticsContext.cs) for  https://github.com/aspnet/Logging/issues/156

Name: `NestedDiagnosticsLogicalContext`

Analogues to [`MappedDiagnosticsContext`](https://github.com/NLog/NLog/blob/master/src/NLog/MappedDiagnosticsContext.cs) and [`MappedDiagnosticsLogicalContext`](https://github.com/NLog/NLog/blob/master/src/NLog/MappedDiagnosticsLogicalContext.cs)

**Comment by 304NotModified** [comment]
fixed

**Comment by snakefoot** [comment]
MDLC is now working, but still missing https://github.com/NLog/NLog/pull/2110

**Comment by snakefoot** [comment]
Resolved with #2110 ?

**Comment by 304NotModified** [comment]
yes your right! thanks!
