### ISSUE TITLE
StackOverflowException when File target's fileName uses ${var:mydir} instead of ${mydir}

### ISSUE THREAD

**Issue by AndreGleichner** [NLog/NLog#1381]
I'm using a variable "mydir" to hold the actual path where a file target should create its log file.
When referencing it via ${var:mydir} it throws a StackOverflowException.
When using the (no longer recomended?) `${mydir}` it works.
Have used NLog 4.2.3 before which works fine with `${var:mydir}`.
My actual NLog.config is much more complicated, so that the use of a variable makes sense...

**Type**: Bug
**NLog version**: 4.3.0
**Platform**: .Net 4.0 on Win10

**Current NLog config** (xml or C#, if relevant)

```xml
<?xml version="1.0" encoding="utf-8" ?>
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="http://www.nlog-project.org/schemas/NLog.xsd NLog.xsd"
      autoReload="true"
      throwExceptions="false"
      internalLogLevel="Trace" internalLogFile="c:\temp\nlog-internal.log" >
    
    <variable name="mydir" value="c:\temp\HelloNlog"/>
    <targets>
        <target name="fileAll" xsi:type="File" fileName="${var:mydir}\Test.log" />
    </targets>
    <rules>
        <logger name="*" writeTo="fileAll" />
    </rules>
</nlog>

```

In case of a BUG:

- What is the current result? StackOverflowException
- What is the expected result? 
- Did you checked the [Internal log](https://github.com/NLog/NLog/wiki/Internal-Logging)?
 Yes, but gives no clear indication of what went wrong.
- Please post full exception details (message, stacktrace, inner exceptions)
 See below.
- Are there any work arrounds? yes, use ${mydir} instead of ${var:mydir}
- Is there a version in which it did worked? 4.2.3
- Can you help us by writing an unit test? 
 Don't know enough about NLog's inner workings.

It recurses endlessly invoking NLog.Targets.FileTarget.FileName.set.
While doing a short debug session, I wasn't able to spot the root cause.

**Stacktrace:**

```
 	...
 	NLog.dll!**NLog.Targets.FileTarget.FileName.set**(NLog.Layouts.Layout value) Line 240
 	NLog.dll!NLog.Internal.PropertyHelper.SetPropertyFromString(object obj, string propertyName, string value, NLog.Config.ConfigurationItemFactory configurationItemFactory) Line 93
 	NLog.dll!NLog.Config.XmlLoggingConfiguration.ConfigureObjectFromAttributes(object targetObject, NLog.Config.NLogXmlElement element, bool ignoreType) Line 1109
 	NLog.dll!NLog.Config.XmlLoggingConfiguration.ParseTargetElement(NLog.Targets.Target target, NLog.Config.NLogXmlElement targetElement) Line 802
 	NLog.dll!NLog.Config.XmlLoggingConfiguration.ParseTargetsElement(NLog.Config.NLogXmlElement targetsElement) Line 778
 	NLog.dll!NLog.Config.XmlLoggingConfiguration.ParseNLogElement(NLog.Config.NLogXmlElement nlogElement, string filePath, bool autoReloadDefault) Line 560
 	NLog.dll!NLog.Config.XmlLoggingConfiguration.ParseTopLevel(NLog.Config.NLogXmlElement content, string filePath, bool autoReloadDefault) Line 478
 	NLog.dll!NLog.Config.XmlLoggingConfiguration.Initialize(System.Xml.XmlReader reader, string fileName, bool ignoreErrors) Line 383
 	NLog.dll!NLog.Config.XmlLoggingConfiguration.XmlLoggingConfiguration(string fileName, bool ignoreErrors, NLog.LogFactory logFactory) Line 129
 	NLog.dll!NLog.Config.XmlLoggingConfiguration.XmlLoggingConfiguration(string fileName, NLog.LogFactory logFactory) Line 105
 	NLog.dll!NLog.LogFactory.LoadLoggingConfiguration(string configFile) Line 1043
 	NLog.dll!NLog.LogFactory.Configuration.get() Line 186
 	NLog.dll!NLog.LogManager.Configuration.get() Line 157
 	NLog.dll!NLog.LayoutRenderers.VariableLayoutRenderer.Append(System.Text.StringBuilder builder, NLog.LogEventInfo logEvent) Line 73
 	NLog.dll!NLog.LayoutRenderers.LayoutRenderer.Render(System.Text.StringBuilder builder, NLog.LogEventInfo logEvent) Line 161
 	NLog.dll!NLog.Layouts.SimpleLayout.GetFormattedMessage(NLog.LogEventInfo logEvent) Line 281
 	NLog.dll!NLog.Layouts.Layout.Render(NLog.LogEventInfo logEvent) Line 140
 	NLog.dll!NLog.Targets.FileTarget.GetCleanedFileName(NLog.LogEventInfo logEvent) Line 871
 	NLog.dll!NLog.Targets.FileTarget.RefreshFileArchive() Line 607
 	NLog.dll!**NLog.Targets.FileTarget.FileName.set**(NLog.Layouts.Layout value) Line 240
 	NLog.dll!NLog.Internal.PropertyHelper.SetPropertyFromString(object obj, string propertyName, string value, NLog.Config.ConfigurationItemFactory configurationItemFactory) Line 93
 	NLog.dll!NLog.Config.XmlLoggingConfiguration.ConfigureObjectFromAttributes(object targetObject, NLog.Config.NLogXmlElement element, bool ignoreType) Line 1109
 	NLog.dll!NLog.Config.XmlLoggingConfiguration.ParseTargetElement(NLog.Targets.Target target, NLog.Config.NLogXmlElement targetElement) Line 802
 	NLog.dll!NLog.Config.XmlLoggingConfiguration.ParseTargetsElement(NLog.Config.NLogXmlElement targetsElement) Line 778
 	NLog.dll!NLog.Config.XmlLoggingConfiguration.ParseNLogElement(NLog.Config.NLogXmlElement nlogElement, string filePath, bool autoReloadDefault) Line 560
 	NLog.dll!NLog.Config.XmlLoggingConfiguration.ParseTopLevel(NLog.Config.NLogXmlElement content, string filePath, bool autoReloadDefault) Line 478
 	NLog.dll!NLog.Config.XmlLoggingConfiguration.Initialize(System.Xml.XmlReader reader, string fileName, bool ignoreErrors) Line 383
 	NLog.dll!NLog.Config.XmlLoggingConfiguration.XmlLoggingConfiguration(string fileName, bool ignoreErrors, NLog.LogFactory logFactory) Line 129
 	NLog.dll!NLog.Config.XmlLoggingConfiguration.XmlLoggingConfiguration(string fileName, NLog.LogFactory logFactory) Line 105
 	NLog.dll!NLog.LogFactory.LoadLoggingConfiguration(string configFile) Line 1043
 	NLog.dll!NLog.LogFactory.Configuration.get() Line 186
 	NLog.dll!NLog.LogFactory.GetLogger(NLog.LogFactory.LoggerCacheKey cacheKey) Line 989
 	NLog.dll!NLog.LogFactory.GetLogger(string name) Line 446
 	NLog.dll!NLog.LogManager.GetCurrentClassLogger() Line 190
 	TestNlog.exe!TestNlog.Program.Program() Line 11

```

**Comment by 304NotModified** [comment]
Thanks for this report! Will check and fix this soon

**Comment by 304NotModified** [comment]
hey @bhaeussermann can you help me with this? Thanks!

**Comment by 304NotModified** [comment]
I think we have to pass the filename (`value`) to `RefreshFileArchive` (and maybe `RefreshArchiveFilePatternToWatch`

**Comment by 304NotModified** [comment]
changes made in:

- https://github.com/NLog/NLog/commit/00164c5efa76773775cb3dda60000dab2a19fe48#diff-ed0a3fc25ad7408a5b63501fa77dbe69R219 and 
- https://github.com/NLog/NLog/commit/59602cf9be1e1d23a6710eee69a8de8f22309818#diff-ed0a3fc25ad7408a5b63501fa77dbe69R234

**Comment by 304NotModified** [comment]
Of course this bug is a combination of things.

1. There is are unwanted side effects of setters in the FileTarget (see above)
2. But also the VariableLayoutRender uses code which isn't optimal - a layout renderer should never use the LogManager.

2. has been solved in #1383 

@AndreGleichner can you confirm that if I upload a RC to Nuget?

**Comment by 304NotModified** [comment]
> When using the (no longer recomended?) ${mydir} it works.

about the "no longer recomended", `${mydir}` are more like constants then like variables - those aren't dynamic and hard to change from value. BUT there is a performance trade-off, as the `${mydir}` are resolved at config time and so there is no new rendering needed at runtime (in contract to `${var:mydir}` ).

**Comment by 304NotModified** [comment]
https://www.nuget.org/packages/NLog/4.3.1-rc1 

Please confirm. Thanks!

**Comment by AndreGleichner** [comment]
The actual StackOverflowException got fixed with 4.3.1-rc1, but now it tries creating the logfile in c:\Test.log instead of c:\temp\HelloNlog\Test.log.

Again, when not using ${var:...} it works.

Didn't know that ${var:...} are performing worse, I somehow interpreted this https://github.com/NLog/NLog/wiki/Configuration-file#vars-since-nlog-41 as a recomendation towards that new syntax.

**Comment by d3prok** [comment]
I can confirm the behavior described by @AndreGleichner, we had to downgrade to version 4.2.3.

**Comment by 304NotModified** [comment]
> The actual StackOverflowException got fixed with 4.3.1-rc1, but now it tries creating the logfile in c:\Test.log instead of c:\temp\HelloNlog\Test.log.

So it's not solved well



> I can confirm the behavior described by @AndreGleichner, we had to downgrade to version 4.2.3.

Thanks for the report, this is first prio to fix this

**Comment by 304NotModified** [comment]
This has been fixed in NLog 4.3.1 and is now online: https://www.nuget.org/packages/NLog/4.3.1
