### ISSUE TITLE
Bug in 4.3.0 Thread was being aborted

### ISSUE THREAD

**Issue by nickjudson** [NLog/NLog#1385]
Bug:

**NLog version**: 4.3.0

**Platform**: .Net 4.5

**Current NLog config** (xml or C#, if relevant)

```xml
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" autoReload="true">
    <extensions>
      <add prefix="share" assembly="Connexion.Share" />
    </extensions>
    <targets>
      <target name="EventHistoryLogger" xsi:type="Share.EventHistoryLogger" layout="[${logger}] - ${share.TruncateLayout:${message}}" />
      <target name="AuditFileLogger" xsi:type="File" header = "------ Connexion v${assembly-version} ------" layout="${longdate} (${threadid}) ${level} ${event-context:eventId} ${event-context:auditedUser} (${event-context:auditedEndpoint}) [${logger}] ${share.TruncateLayout:${message}} ${exception:format=tostring}" fileName="${specialFolder:folder=CommonApplicationData}\ConnexionV14\Audit\Connexion.Audit.txt" archiveNumbering="Date" archiveEvery="Day" archiveDateFormat="yyyyMMdd" maxArchiveFiles="10" enableArchiveFileCompression="true" keepFileOpen="true" />
      <target name="UserFileLogger" xsi:type="File" header = "------ Connexion v${assembly-version} ------" layout="${longdate} (${threadid}) ${level} ${event-context:eventId} [${logger}] ${share.TruncateLayout:${message}} ${exception:format=tostring}" fileName="${specialFolder:folder=CommonApplicationData}\ConnexionV14\logs\Connexion.User.txt" archiveNumbering="Date" archiveEvery="Day" archiveDateFormat="yyyyMMdd" maxArchiveFiles="30" enableArchiveFileCompression="true" keepFileOpen="true" />
      <target name="FileLogger" xsi:type="File" header = "------ Connexion v${assembly-version} ------" layout="${longdate} (${threadid}) ${level} ${event-context:eventId} [${logger}] ${share.TruncateLayout:${message}} ${exception:format=tostring}" fileName="${specialFolder:folder=CommonApplicationData}\ConnexionV14\logs\Connexion.txt" archiveNumbering="Date" archiveEvery="Day" archiveDateFormat="yyyyMMdd" maxArchiveFiles="10" enableArchiveFileCompression="true" keepFileOpen="true" />
      <target name="Eventlog" xsi:type="EventLog" layout="${level} [${logger}] ${share.TruncateLayout:${message}} ${exception:format=tostring}" eventID="${event-context:eventId}" source="Connexion" log="Application" />
      <target name="ColoredConsole" xsi:type= "ColoredConsole" layout="${longdate} (${threadid}) ${level} [${logger}] ${event-context:eventId} ${share.TruncateLayout:${message}} ${exception:format=tostring}" />
    </targets>
    <rules>
      <logger name="*" minlevel="Debug" writeTo="AuditFileLogger" >
        <filters>
          <share.auditEventFilter />
        </filters>
      </logger>
      <logger name="*" minlevel="Info" writeTo="EventHistoryLogger" />
      <logger name="*" minlevel="Debug" writeTo="UserFileLogger" >
        <filters>
          <share.userEventFilter action="logfinal"/>
        </filters>
      </logger>
      <logger name="*" minlevel="Debug" writeTo="FileLogger" />
      <logger name="*" minlevel="Error" writeTo="EventLog" />
      <logger name="*" minlevel="Debug" writeTo="ColoredConsole" />
    </rules>
  </nlog>
```

- What is the current result?

Exception (see below).

- What is the expected result?

No exception (version 4.2.3 works as expected).

- Did you checked the [Internal log](https://github.com/NLog/NLog/wiki/Internal-Logging)?

[log.txt](https://github.com/NLog/NLog/files/226656/log.txt)

- Is there a version in which it did worked? 4.2.3

```
System.Threading.ThreadAbortException: Thread was being aborted.
   at System.Threading.Thread.SleepInternal(Int32 millisecondsTimeout)
   at System.Threading.Thread.Sleep(Int32 millisecondsTimeout)
   at NLog.Targets.FileTarget.<RefreshArchiveFilePatternToWatch>b__1()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

```

**Comment by 304NotModified** [comment]
Thanks for this report! Will fix this soon!

**Comment by 304NotModified** [comment]
So what Related #1381

**Comment by 304NotModified** [comment]
working on this

**Comment by 304NotModified** [comment]
This has been fixed in NLog 4.3.1 and is now online: https://www.nuget.org/packages/NLog/4.3.1

**Comment by jonreis** [comment]
I have 4.3.1 installed and I still see this problem. I don't think the code solves the problem because there is no Thread.ResetAbort being called so the exception is rethrown right after the catch. 
Please see: http://stackoverflow.com/questions/1856286/threadabortexception

**Comment by 304NotModified** [comment]
Thanks! Will fix this now!

**Comment by jonreis** [comment]
Also, I have noticed this thread causes our application to never exit. It should be set as a background thread. The default is a foreground thread. Please see: https://msdn.microsoft.com/en-us/library/system.threading.thread.isbackground(v=vs.110).aspx

**Comment by 304NotModified** [comment]
so `IsBackground = false` before start?

**Comment by jonreis** [comment]
yes, definitely or the thread will never exit when the application shuts down.
