### ISSUE TITLE
FileTarget fails to write to primary log file if moving to archive fails.

### ISSUE THREAD

**Issue by mzboray** [NLog/NLog#1645]
I am seeing an issue that comes up intermittently where FileTarget does not write to the log. I was able to catch this once and turn on internal logging to get a better idea of the issue. From I can tell moving to the archive file was failing because the archive file already exists which in turn is causing the FileTarget not write to the primary log file.

First, some background on when this issue seems to come up. We have a windows service that writes to a file log. This issue seems to happen when the service has been off for a long time and some one upgrades and starts the service again. From what I can tell in the internal log (see below) there is already an archive file from say the last time the service ran on 08/04/2016. Then after the service starts say on 09/16/2016, NLog detects that there are still some messages from 08/04/2016 (these messages are in the log file) and the last modify date is also 08/04/2016. However NLog does not try to append these to an existing archive, but will just try to Move and this will fail.

**Type**: Bug
**NLog version**: 4.3.5
**Platform**: .Net 4.5
**Current NLog config**
```xml
  <nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" autoReload="true" internalLogFile="c:\nlog\internallog.txt" internalLogLevel="Trace">
    <variable name="fmt" value="${longdate}|${level:uppercase=true}|${logger}|${threadid}|${trim-whitespace:inner=${message} ${all-event-properties}${newline}${exception:format=tostring}}" />
    <variable name="logPath" value="${specialfolder:folder=CommonApplicationData}\MyProduct\Logs" />
    <targets async="true">
      <target name="logfile" xsi:type="File" fileName="${logPath}\log.txt"
              archiveFileName="${logPath}\archives\log-{#}.txt" keepFileOpen="false"
              createDirs="true" archiveEvery="Day" archiveNumbering="Date" maxArchiveFiles="7"
              concurrentWrites="false" layout="${fmt}" />
    </targets>
    <rules>
      <logger name="*" minlevel="Trace" writeTo="logfile" />
    </rules>
  </nlog>
```

In case of a BUG:

- What is the current result?
All logging to the primary log file fails.

- What is the expected result?
Logs to be written to the primary log file to continue even if moving/appending to the archive fails.

- Did you checked the [Internal log](https://github.com/NLog/NLog/wiki/Internal-Logging)?
Yes. Relevant details:

> 2016-09-16 14:16:15.3470 Trace Calculating archive date. Last write time: 08/04/2016 15:29:38; Previous log event time: 
> 2016-09-16 14:16:15.3470 Trace Using last write time
> 2016-09-16 14:16:15.3470 Info Archiving C:\ProgramData\MyProduct\Logs\log.txt to C:\ProgramData\MyProduct\Logs\archives\log-20160804.txt
> 2016-09-16 14:16:15.3632 Error Error has been raised. Exception: System.IO.IOException: Cannot create a file when that file already exists.
> 
>    at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
>    at System.IO.File.InternalMove(String sourceFileName, String destFileName, Boolean checkHost)
>    at NLog.Targets.FileTarget.ArchiveFile(String fileName, String archiveFileName)
>    at NLog.Targets.FileTarget.ArchiveByDate(String fileName, String pattern, LogEventInfo logEvent)
>    at NLog.Targets.FileTarget.ProcessLogEvent(LogEventInfo logEvent, String fileName, Byte[] bytesToWrite)
>    at NLog.Targets.FileTarget.FlushCurrentFileWrites(String currentFileName, LogEventInfo firstLogEvent, MemoryStream ms, List`1 pendingContinuations)

- Please post full exception details (message, stacktrace, inner exceptions)
See above.
- Are there any work arounds?
Deleting the primary log file will resume logging, but this is problematic because often you are coming to the log to find the cause of an issue and nothing has been logged for some time.
- Is there a version in which it did worked? I have not been able to exactly reproduce this, but I have seen it happen multiple times.
- Can you help us by writing an unit test? I am willing to help with testing or whatever, if needed.

**Comment by 304NotModified** [comment]
We are releasing 4.3.9 soon. Could you test with that version? A related error has been fixed (also " Cannot create a file when that file already exists."), see https://github.com/NLog/NLog/issues/1608

**Comment by 304NotModified** [comment]
NLog 4.3.9 is live! https://www.nuget.org/packages/NLog/4.3.9

**Comment by mzboray** [comment]
I tried 4.3.9 in a very simple reproduction where I set the file write/access times to be in line with my observations when this happens. This issue is not fixed in this version.

Here is a more straightforward although artificial repro in code:

    class Program
    {
        private static readonly Logger _Logger = LogManager.GetLogger("Main");

        static void Main(string[] args)
        {
            // set log file access times the same way as when this issue comes up.
            string logFile = "log.txt";
            File.WriteAllText(logFile, "some content");
            var oldTime = DateTime.Now.AddDays(-2);
            File.SetCreationTime(logFile, oldTime);
            File.SetLastWriteTime(logFile, oldTime);
            File.SetLastAccessTime(logFile, oldTime);

            File.WriteAllText(string.Format("log-{0}.txt", oldTime.ToString("yyyyMMdd")), "some archive content");

            // enable internal logging to the console
            InternalLogger.LogToConsole = true;
            InternalLogger.LogLevel = LogLevel.Error;

            // configure nlog
            var fileTarget = new FileTarget("file")
            {
                FileName = "log.txt",
                ArchiveEvery = FileArchivePeriod.Day,
                ArchiveFileName = "log-{#}.txt",
                ArchiveNumbering = ArchiveNumberingMode.Date,
            };

            var rule = new LoggingRule("*", LogLevel.Trace, fileTarget);

            var config = new LoggingConfiguration();
            config.AddTarget(fileTarget);
            config.LoggingRules.Add(rule);

            LogManager.Configuration = config;

            // write
            _Logger.Info("Log message");
        }
    }

Another thing that seems odd is that some how there is already an archive file for some past date AND nlog is still trying to archive. I'm not sure how that happens. However, this particular issue could probably be resolved by protected the File.Move when archiving. I'm not sure what the proper handling should be, but not logging the current message seems worse than say duplicating the some contents of the archive file or creating an alternate archive file.

**Comment by 304NotModified** [comment]
Thanks! will check now!

**Comment by 304NotModified** [comment]
This is indeed an issue in NLog 4.3

Work arounds are: move to NLog 4.2 or use DateAndSequence.

Will try to fix this, but won't be today.

**Comment by mzboray** [comment]
Ok. I think we can use DateAndSequence as a work around. Thanks for looking into this so quickly.

**Comment by 304NotModified** [comment]
So for the correct solution, I think we need to append to the archive file?

**Comment by mzboray** [comment]
Yes. I didn't grab the contents of archives when I saw this last time, but I *think* the contents of the primary where already there (weird, I know), so some of the log messages would end up duplicated. I would rather there be some duplicates in the archive file than losing any new log messages.

**Comment by chrisdrobison** [comment]
We are seeing this issue as well

**Comment by rbouny** [comment]
+1

**Comment by 304NotModified** [comment]
I could use some help here. Tried to append to the archive, but failed. Not sure what is wrong. 

https://github.com/NLog/NLog/pull/1680

**Comment by mzboray** [comment]
Those changes look correct and I tested it out with the example code I provided. It seems to work correctly. How is it failing?

**Comment by 304NotModified** [comment]
Wow is it working? (the code, not the test).

Then it should be a flush/async problem in the unit test.

**Comment by mzboray** [comment]
Looks like it works fine to me. I didn't try running the unit tests.

**Comment by 304NotModified** [comment]
Ok will try to get the unit test fixed (doesn't seems complete either, lost a commit I guess), and push as new version soon. Feedback if this also works for others (when compiled from source), would be helpful !

**Comment by 304NotModified** [comment]
OK I think it got it working. There was a bug then the BOM was also copied. Fixed that for UTF8.
