### ISSUE TITLE
Unable to create/write to log on linux server using NLog 5.0.0-beta01 + beta02

### ISSUE THREAD

**Issue by sdaub** [NLog/NLog#1737]
**NLog version**: 5.0.0-beta01

**Platform**: .NET Core 

**Current NLog config** (xml or C#, if relevant)

```xml
<?xml version="1.0" encoding="utf-8" ?>
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      autoReload="true"
      internalLogLevel="Warn"
      internalLogFile="c:\temp\internal-nlog.txt">

  <extensions>
    <add assembly="PlayAuth.Common" />
  </extensions>
  
  <variable name="correlationLayout" value="${when:when=length('${correlationId}') &gt; 0:inner= Id=${correlationId},}" />
  <variable name="messageLayout" value="Message=${replace-newlines:Message=${truncated:Limit=10000:inner=${message}}" />
  <variable name="exceptionLayout" value="${when:when=length('${exception}') &gt; 0:inner= Type=${exception:Format=Type} Exception=${replace-newlines:${exception:maxInnerExceptionLevel=4}}}" />
    <targets>
    <target xsi:type="File" name="splunk-log" fileName="log\nlog-own.log"
             layout="${longdate}|${event-properties:item=EventId.Id}|${logger}|${uppercase:${level}}|  ${message} ${exception}" />
    
    <target name="splunkfileAsync" xsi:type="AsyncWrapper" queueLimit="20000" overflowAction="Discard">
      <target xsi:type="File" name="file"
              layout="[${date:universalTime=true:format=O}] Level=${level}, Category=${logger},${correlationLayout} ${messageLayout} ${exceptionLayout}"
              fileName="/var/log/playauth.log" archiveFileName="/var/log/log-own.log" archiveAboveSize="52428800" archiveNumbering="Sequence" maxArchiveFiles="2" />
    </target>
    
    <target xsi:type="ColoredConsole"
          name="console2"
          layout="${longdate} ${pad:padding=5:inner=-${level}-} Category=${logger}, ${message}"
          useDefaultRowHighlightingRules="True"
          errorStream="True">
      <highlight-word text="-Warn-"  foregroundColor="DarkYellow" />
      <highlight-word text="-Error-"  foregroundColor="DarkMagenta" />
      <highlight-word text="-Fatal-"  foregroundColor="DarkRed" backgroundColor="White"/>
    </target>
    <target xsi:type="Null" name="blackhole" />
  </targets>

  <rules>
    <!--Skip Microsoft logs and so log only own logs-->
    <logger name="Microsoft.*" minlevel="Trace" writeTo="blackhole" final="true" />

    <!--This line below should work to prevent verbose output from a class. This is not working currently
    so the workaround it to use the class name instead of namespace.classname.  More info:
    https://github.com/NLog/NLog/issues/1379#issuecomment-235696767.
    -->
    <logger name="ConfigurationService" levels="Trace,Debug" final="true"/>
    
    <!-- Turn down logging on things we don't care about-->
    <logger name="Enyim.*" levels="Trace,Debug" writeTo="blackhole" final="true" />   
    
    <logger name="*" minlevel="Trace" writeTo="console2" />
    <logger name="*" minlevel="Trace" writeTo="splunkfileAsync" />
  </rules>
</nlog>


```

I am working with our server team to set up a Linux server in AWS to run a .NET Core web api project. A couple weeks ago I create an image using Docker and verified the solution was working correctly, including logging with NLog to a file /var/log/playauth.log.  This worked as expected.

Yesterday NLog 5.0.0-beta01 was released and I quickly upgraded my project.json files to use the new version. Everything worked fine on my Windows development box.  

When working with the server team yesterday to finish the deployment process, we were not getting the log file as expected.  We tried a number of different filenames, and paths to rule out some permissions and naming problems.  Although the actual log file was not created, the internalLogFile setting on the NLog node was being used to create that log file.  One error found there was: 

> 2016-11-01 21:05:49.5071 Error Error initializing target 'File Target[file]'. Exception: System.ArgumentNullException: Value cannot be null.
Parameter name: path1
   at System.IO.Path.Combine(String path1, String path2)
   at NLog.Targets.FileTarget.RefreshFileArchive()
   at NLog.Targets.FileTarget.InitializeTarget()
   at NLog.Targets.Target.Initialize(LoggingConfiguration configuration)

 Taking a wild guess, I changed the projects back to using NLog 4.4.0-betaV15.  Things started working.  

Today, logging has been working as expected.  I tried upgrading again to NLog 5.0.0-beta01 and logging stopped and the only change was changing the version of NLog.  Changing it back to 4.4.0-betaV15 got it working again.

The Runtime for this application is:  "debian.8-x64".

Is anyone else experiencing issues like this?

**Comment by 304NotModified** [comment]
I see this also in the unit tests. Dunno which one is null

**Comment by 304NotModified** [comment]
Working on this

**Comment by 304NotModified** [comment]
should be fixed in beta2: https://www.nuget.org/packages/NLog/5.0.0-beta02

please confirm! Thanks!

**Comment by sdaub** [comment]
Thank your for the quick turnaround on this! 
Unfortunately that did not resolve the issue, although now the log shows a different error:

2016-11-03 14:47:11.3504 Warn Unused target detected. Add a rule for this target to the configuration. TargetName: splunk-log
2016-11-03 14:47:11.3693 Warn Unused target detected. Add a rule for this target to the configuration. TargetName: file
2016-11-03 14:47:11.6459 Error Error has been raised. Exception: System.IO.IOException: The filename, directory name, or volume label syntax is incorrect.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.Threading.Mutex.MutexTryCodeHelper.MutexTryCode(Object userData)
   at System.Runtime.CompilerServices.RuntimeHelpers.ExecuteCodeWithGuaranteedCleanup(TryCode code, CleanupCode backoutCode, Object userData)
   at System.Threading.Mutex.CreateMutexWithGuaranteedCleanup(Boolean initiallyOwned, String name, Boolean& createdNew, SECURITY_ATTRIBUTES secAttrs)
   at NLog.Internal.FileAppenders.RetryingMultiProcessFileAppender.CreateArchiveMutex()
   at NLog.Internal.FileAppenders.BaseFileAppender..ctor(String fileName, ICreateFileParameters createParameters)
   at NLog.Internal.FileAppenders.RetryingMultiProcessFileAppender.Factory.NLog.Internal.FileAppenders.IFileAppenderFactory.Open(String fileName, ICreateFileParameters parameters)
   at NLog.Internal.FileAppenders.FileAppenderCache.AllocateAppender(String fileName)
   at NLog.Targets.FileTarget.WriteToFile(String fileName, LogEventInfo logEvent, Byte[] bytes, Boolean justData)
   at NLog.Targets.FileTarget.ProcessLogEvent(LogEventInfo logEvent, String fileName, Byte[] bytesToWrite)
   at NLog.Targets.FileTarget.FlushCurrentFileWrites(String currentFileName, LogEventInfo firstLogEvent, MemoryStream ms, List`1 pendingContinuations)
2016-11-03 14:47:11.7954 Error Error has been raised. Exception: System.IO.IOException: The filename, directory name, or volume label syntax is incorrect.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.Threading.Mutex.MutexTryCodeHelper.MutexTryCode(Object userData)
   at System.Runtime.CompilerServices.RuntimeHelpers.ExecuteCodeWithGuaranteedCleanup(TryCode code, CleanupCode backoutCode, Object userData)
   at System.Threading.Mutex.CreateMutexWithGuaranteedCleanup(Boolean initiallyOwned, String name, Boolean& createdNew, SECURITY_ATTRIBUTES secAttrs)
   at NLog.Internal.FileAppenders.RetryingMultiProcessFileAppender.CreateArchiveMutex()
   at NLog.Internal.FileAppenders.BaseFileAppender..ctor(String fileName, ICreateFileParameters createParameters)
   at NLog.Internal.FileAppenders.RetryingMultiProcessFileAppender.Factory.NLog.Internal.FileAppenders.IFileAppenderFactory.Open(String fileName, ICreateFileParameters parameters)
   at NLog.Internal.FileAppenders.FileAppenderCache.AllocateAppender(String fileName)
   at NLog.Targets.FileTarget.WriteToFile(String fileName, LogEventInfo logEvent, Byte[] bytes, Boolean justData)
   at NLog.Targets.FileTarget.ProcessLogEvent(LogEventInfo logEvent, String fileName, Byte[] bytesToWrite)
   at NLog.Targets.FileTarget.FlushCurrentFileWrites(String currentFileName, LogEventInfo firstLogEvent, MemoryStream ms, List`1 pendingContinuations)
2016-11-03 14:47:12.4709 Error Error has been raised. Exception: System.IO.IOException: The filename, directory name, or volume label syntax is incorrect.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.Threading.Mutex.MutexTryCodeHelper.MutexTryCode(Object userData)
   at System.Runtime.CompilerServices.RuntimeHelpers.ExecuteCodeWithGuaranteedCleanup(TryCode code, CleanupCode backoutCode, Object userData)
   at System.Threading.Mutex.CreateMutexWithGuaranteedCleanup(Boolean initiallyOwned, String name, Boolean& createdNew, SECURITY_ATTRIBUTES secAttrs)
   at NLog.Internal.FileAppenders.RetryingMultiProcessFileAppender.CreateArchiveMutex()
   at NLog.Internal.FileAppenders.BaseFileAppender..ctor(String fileName, ICreateFileParameters createParameters)
   at NLog.Internal.FileAppenders.RetryingMultiProcessFileAppender.Factory.NLog.Internal.FileAppenders.IFileAppenderFactory.Open(String fileName, ICreateFileParameters parameters)
   at NLog.Internal.FileAppenders.FileAppenderCache.AllocateAppender(String fileName)
   at NLog.Targets.FileTarget.WriteToFile(String fileName, LogEventInfo logEvent, Byte[] bytes, Boolean justData)
   at NLog.Targets.FileTarget.ProcessLogEvent(LogEventInfo logEvent, String fileName, Byte[] bytesToWrite)
   at NLog.Targets.FileTarget.FlushCurrentFileWrites(String currentFileName, LogEventInfo firstLogEvent, MemoryStream ms, List`1 pendingContinuations)


The rest of the internal log file appears to be just these same entries repeating.
The NLog.config file is the same as in the original post.

**Comment by 304NotModified** [comment]
strange, as the unit test succeeds. Unfortunately  can't get the unit tests running on Travis (Mac/Linux)

**Comment by snakefoot** [comment]
Not sure about this, but could failing to create mutex be related to: https://github.com/dotnet/coreclr/issues/3422 ? (Though different exception)

**Comment by 304NotModified** [comment]
working on this.

Frustrating enough, can't find the .NET core class references.

**Comment by 304NotModified** [comment]
found it: https://docs.microsoft.com/en-us/dotnet/core/api/system.threading.mutex#System_Threading_Mutex

Looks indeed to a .NET Core bug.

**Comment by 304NotModified** [comment]
looks like the `/` is also not valid in those names. 
https://github.com/dotnet/coreclr/blob/32f0f9721afb584b4a14d69135bea7ddc129f755/src/pal/tests/palsuite/threading/NamedMutex/test1/namedmutex.cpp#L21

Not documented anywhere.

**Comment by 304NotModified** [comment]
@sdaub could you try "5.0.0-beta03-tryoutMutex": https://www.nuget.org/packages/NLog/5.0.0-beta03-tryoutMutex?

removed all the slashes from the mutex name.

**Comment by sdaub** [comment]
I will try either later tonight or first thing tomorrow and give an update.

Thanks!

**Comment by 304NotModified** [comment]
OK thanks in advance!

**Comment by 304NotModified** [comment]
Got the same error now also on Travis :)

(before the change): https://travis-ci.org/NLog/NLog/builds/173091681

**Comment by sdaub** [comment]
That change got it!  Thinks are working now on the linux server.  

Thanks for getting to the bottom of this.

**Comment by 304NotModified** [comment]
I have hidden the tryout package and released beta3: https://www.nuget.org/packages/NLog/5.0.0-beta03

**Comment by vinaydate** [comment]
@304NotModified When I installed beta04, I encountered same error. Then reading your post above, tried with beta03. And it worked.

One another weird observation is: Each time it makes a log entry, earlier entry is archived. I expected the archival process to be executed daily.

My config is :

```
<target xsi:type="File"
					  concurrentWrites="False"
					  encoding="utf-8"
					  fileName="./logs/logfile.current.txt"
					  archiveOldFileOnStartup="True"
					  maxArchiveFiles="20"
					  archiveNumbering="Date"
					  archiveDateFormat="yyyyMMdd"
					  archiveEvery="Day"
					  layout="${longdate} ${logger} ${message}" />
```

**Comment by 304NotModified** [comment]
This is a regression bug :( 

Something went wrong with merging and the unit tests aren't still reporting correctly from appveyor.

**Comment by 304NotModified** [comment]
See https://github.com/NLog/NLog/issues/1882#issuecomment-269774448

**Comment by 304NotModified** [comment]
Should be fixed in https://www.nuget.org/packages/NLog/5.0.0-beta05-test

Could you please test it? Thanks!

**Comment by 304NotModified** [comment]
I assume this is fixed so closing now.
