### ISSUE TITLE
$(assembly-version) returns .NET framework version iso application version

### ISSUE THREAD

**Issue by vankampenp** [NLog/NLog#2428]
**Type** (choose one):
- Bug

**NLog version**:  4.4.1 Nlog.Web.AspNetCore

**Platform**: .NET Core 
I am using " Version ${assembly-version}"  in the layout

In case of a BUG:
- What is the current result? "Version 4.6.1" , I assume the 4.6.1 is the Microsoft .NET assembly version
- What is the expected result? "Version 7.1.1"  which is the my (asp.net core) project assembly version
According to the tutorial $(assembly-version) should return "The version of the executable in the default application domain." I read this to be the project executable that is executed to run Kestrel with my web site. 
- Did you checked the [Internal log](https://github.com/NLog/NLog/wiki/Internal-Logging)? no
- Are there any work arrounds? no
- Is there a version in which it did worked? new user
- Can you help us by writing an unit test?no

The .NET assembly version is hardly relevant, no reason ever to log this. The App assembly version is.

**Comment by 304NotModified** [comment]
I think this is fixed inhttps://www.nuget.org/packages/NLog.Web.AspNetCore/4.5.0-beta04, could you check that please?

**Comment by vankampenp** [comment]
Hi, I am using .NET Core 1.1. The beta does not fix it for that.
Thanks,
Pieter

**Comment by vankampenp** [comment]
Hi I migrated the project to .NET Core 2.0 on .NET Framework (I can't yet go to .NET Standard 2.0). This did not change the result unfortunately.

**Comment by 304NotModified** [comment]
could you please try with NLog 4.5 beta on .net standard 2?

It should work, the code ithe same as .NET 4.5 etc (Microsoft ported it to .NET standard 2), see
https://github.com/NLog/NLog/blob/master/src/NLog/LayoutRenderers/AssemblyVersionLayoutRenderer.cs

**Comment by vankampenp** [comment]
Hi Julian,
Yes with .net standard 2 it works! But I can’t go there for my app as of yet, as I am missing some API’s that are promised for 2.1.

In net standard 2 this is what I have in program.cs:

           public static void Main(string[] args)
        {

            Logger logger= NLogBuilder.ConfigureNLog("NLog.config").GetCurrentClassLogger();

            try
            {
                logger.Debug("init main");
                BuildWebHost(args).Run();
            }
            catch (Exception e)
            {
                //NLog: catch setup errors
                logger.Error(e, "Stopped program because of exception");
                throw;
            }
        }
In .net 4.6.1 with asp.net core 2.0 this is my Main:

       private static readonly Logger Logger = LogManager.GetCurrentClassLogger();

        public static void Main(string[] args)
        {

            try
            {
                Logger.Debug("init main");
  BuildWebHost(args).Run();
            }
            catch (Exception e)
            {
                //NLog: catch setup errors
                Logger.Error(e, "Stopped program because of exception");
                throw;
            }
        }
The test web app Net Standard 2 gives the assembly version 1.0.0, net framework returns 4.6.1

Thanks,

Pieter

**Comment by 304NotModified** [comment]
> The test web app Net Standard 2 gives the assembly version 1.0.0, net framework returns 4.6.1

you could also use NLog 4.5 with .NET 4.6.1?

**Comment by vankampenp** [comment]
Yes, I am using Asp.Net Core 2.0 with .NET 4.6.1, now with Nlog 4.5.
With the code above it starts logging with "init main". I still needed to include
   //add NLog.Web
     app.AddNLogWeb();
in startup.Configure to get the web layout parameters. 

I would use standard 2.0 if I could, but as explained that is not yet possible.
When I started the bug, I was using Asp.Net Core 1.1 with .NET 4.61. with Nlog 4.4.1 I migrated the site to Core 2.0 because you asked me to test it 👍, surprisingly I was done in 3 hours.

**Comment by 304NotModified** [comment]
> With the code above it starts logging with "init main". I still needed to include
> //add NLog.Web
> app.AddNLogWeb();
> in startup.Configure to get the web layout parameters.

that's correct



> When I started the bug, I was using Asp.Net Core 1.1 with .NET 4.61.

It's a bit unclear to me - is this also a bug with Asp.Net Core 1.1 with .NET 4.61. + NLog 4.5 rc?  (can i close this issue?)

**Comment by vankampenp** [comment]
It is  a bug, with:
1) Nlog 4.4.1, Asp.Net Core 1.1, .NET Framework 4.6.1
2)  Nlog 4.5.0beta04 with Asp.Net Core 2.0 with .NET Framework 4.6.1
It is not a bug with: 
3)Nlog 4.5.0beta04 with  Asp.Net Core 2.0 with .NET Standard 2.0 
I will test it with NLog 4.5 rc as soon as it is on Nuget
For me it would be good if you could solve 2)

**Comment by snakefoot** [comment]
Looked at the code and created https://github.com/NLog/NLog.Web/issues/222

**Comment by 304NotModified** [comment]
Fixed in Nlog.Web.AspNetCore 4.5 rc1

**Comment by vankampenp** [comment]
Hi I tested it with 4.5 rc1 and can confirm it is solved.

Thanks!

**Comment by 304NotModified** [comment]
thanks for confirming!
