### ISSUE TITLE
AsyncTargetWrapper.ProcessPendingEvents use almost all threads from ThreadPool

### ISSUE THREAD

**Issue by Karnah** [NLog/NLog#3789]
**NLog version**: 4.6.7

**Platform**: .NET Framework 4.8

**Current NLog config** (xml or C#, if relevant)

```xml
  <targets async="true">
    <target xsi:type="File"
            name="FatalsOnlyTextLog"
            fileName="${logDirectory}/fatals.txt"
            archiveFileName="${logDirectory}/old/fatals-{#}.zip"
            archiveNumbering="DateAndSequence"
            archiveDateFormat="yyyy-MM-dd"
            archiveEvery="Day"
            archiveAboveSize="5242880"
            maxArchiveFiles="450"
            encoding="UTF-8"
            autoFlush="false"
            layout="${fatalLogMessage}"
            enableArchiveFileCompression="true" />

    <target xsi:type="File"
            name="TextLog"
            fileName="${logDirectory}/log.txt"
            archiveFileName="${logDirectory}/old/log-{#}.zip"
            archiveNumbering="DateAndSequence"
            archiveDateFormat="yyyy-MM-dd"
            archiveEvery="Day"
            archiveAboveSize="5242880"
            maxArchiveFiles="450"
            encoding="UTF-8"
            autoFlush="false"
            layout="${when:when=(level == LogLevel.Fatal or level == LogLevel.Error):inner=${fatalLogMessage}:else=${logMessage}}"
            enableArchiveFileCompression="true"/>

    <target xsi:type="File"
            name="TraceLog"
            fileName="${logDirectory}/trace.txt"
            archiveFileName="${logDirectory}/old/trace-{#}.zip"
            archiveNumbering="DateAndSequence"
            archiveDateFormat="yyyy-MM-dd"
            archiveEvery="Day"
            archiveAboveSize="5242880"
            maxArchiveFiles="450"
            encoding="UTF-8"
            autoFlush="false"
            layout="${when:when=(level == LogLevel.Fatal or level == LogLevel.Error):inner=${fatalLogMessage}:else=${logMessage}}"
            enableArchiveFileCompression="true"/>

    <target xsi:type="ColoredConsole"
            name="ConsoleWriter"
            layout="(${level:uppercase=true})${time}(${threadid}): ${message}${exception:format=tostring:when=(level == LogLevel.Fatal || level == LogLevel.Error)}"
            useDefaultRowHighlightingRules="true">
    </target>
  </targets>
```

- What is the current result?
In very rare cases almost all threads are blocking by method AsyncTargetWrapper.ProcessPendingEvents

- Did you checked the [Internal log](https://github.com/NLog/NLog/wiki/Internal-Logging)?
No, we didn't know about it

- Please post full exception details (message, stacktrace, inner exceptions)
It's very weird bug which we got only twice for 6 months. Application unexpectedly use all threads from ThreadPool. We create dump and found, that most of threads are blocking by AsyncTargetWrapper.ProcessPendingEvents method: 

![Dump](https://user-images.githubusercontent.com/6525732/73629201-2b032b00-4674-11ea-89b9-3f2969c2582e.png)

If it's important, we have 30-40 log entries per second.

- Are there any workarounds?
No

- Is there a version in which it did work?
I think, no

- Can you help us by writing an unit test?
I don't know how it is possible

**Comment by Karnah** [comment]
Sorry, I found #3621 issue, which fixed in 4.6.8. Can this be the same bug?

**Comment by snakefoot** [comment]
> Sorry, I found #3621 issue, which fixed in 4.6.8. Can this be the same bug?

No it is about having a slow target inside the AsyncWrapper, which cannot keep up where `overflowAction="block" `causes the application to block, because the internal queue is full.

**Comment by snakefoot** [comment]
> > Did you checked the Internal log?
> No, we didn't know about it

Funny how the callstack shows that one thread is stuck writing to NLog InternalLogger-File.

But it should still not cause this explosion in Timer-events.

**Comment by Karnah** [comment]
> Funny how the callstack shows that one thread is stuck writing to NLog InternalLogger-File (`internalLogFile="..."`)

Sorry, we have internal log, but we forgot about it. It have been overwritten and now we cannot check it

**Comment by snakefoot** [comment]
@Karnah Do not know how easy the issue is to reproduce, but if you can, then please check if this pre-release nuget-packages resolves the issue:

https://ci.appveyor.com/project/nlog/nlog/builds/30541343/artifacts

**Comment by Karnah** [comment]
@snakefoot, we tried reproduce on original nuget package, but without success. Bug is very rare and we don't know steps to reproduce. We'll try to come up with something. Many thanks!

**Comment by 304NotModified** [comment]
Ok. I assume this is fixed with https://github.com/NLog/NLog/pull/3790 then.
