### ISSUE TITLE
How can I get NLog to reevaluate the config with variable values set from code?

### ISSUE THREAD

**Issue by rubenwe** [NLog/NLog#694]
Hi.

I tried setting a variable named `logpath` from code. This path is used in the fileName attribute of some of my targets. I would love to change this path during the initialization of my application.

I can set the value of the variable but I couldn't get NLog to reevaluate the fileNames. What would be the propper way of doing this?

Thanks, Ruben.

**Comment by 304NotModified** [comment]
Is everything configured programmatically or with an config file?

Check also #663

**Comment by 304NotModified** [comment]
Is your question answered?

**Comment by winterlude** [comment]
I have exactly the same problem. My console application has to write into different log files on the basis of the input argument. I decided to use a variable, in which I set the value of the input parameter.

This is an excerpt of my NLog config file, where I defined the variable "currentDataTransfer":

    <variable name="currentDataTransfer" value="" />
    <variable name="logDir" value="${basedir}/logs/${processname}"/>
    <targets>
        <target xsi:type="File" name="FileLog" fileName="${logDir}/${currentDataTransfer}_${shortdate}.log"

Then, in the C# main program I set the value of that variable:

    static int Main(string[] args)
    {
        LogManager.Configuration.Variables["currentDataTransfer"] = args[0];

but none of the following instructions works:

        LogManager.ReconfigExistingLoggers();
        LogManager.Configuration.Reload();

**Comment by 304NotModified** [comment]
Hi,

only `ReconfigExistingLoggers()` should work. `LogManager.Configuration.Reload();` will reload the full file and so also the new variable value is lost.

If not, this is probably a bug. Another way to change a property:

```C#
   var target = configuration.FindTargetByName("FileLog") as FileTarget;
   target.FileName = "new_path_to_filename";
```

**Comment by winterlude** [comment]
It doesn't work. 
It seems that the variables I defined into the NLog config file are replaced with their values *before* the application runs, instead of keeping a reference to them. Thus, changing the value of one of them has no effects on the targets because they do not contain references to variables anymore.

I have defined a target named `FileLog` in which I used my custom variables `logDir` and `currentDataTransfer`:

    fileName="${logDir}/${currentDataTransfer}_${shortdate}.log"

If I change programmatically the value of the variables like this:

    LogManager.Configuration.Variables["currentDataTransfer"] = args[0];

and then call

    LogManager.ReconfigExistingLoggers();

nothing happens.

I also tried to re-generate the target's `fileName` (with exactly the same format as in the NLog config file) *after* changing the variable's value, but the instructions

    FileTarget target = LogManager.Configuration.FindTargetByName("FileLog") as FileTarget;
    target.FileName = "${logDir}/${currentDataTransfer}_${shortdate}.log";

return the System.ArgumentException: `LayoutRenderer cannot be found: 'logDir'`.

In additon, if I inspect the value of `target.FileName` I got `'${basedir}/logs/${processname}/_${shortdate}.log'` while I expected `${logDir}/${currentDataTransfer}_${shortdate}.log`. This means that the `fileName` property lost the references to my custom variables and I suppose that this is why it doesn't work.

**Comment by 304NotModified** [comment]
when you set `target.FileName` you can't use variables to bad. 

So you have to read in C# you current `${logDir}` and create a `string` without `${logDir}`

**Comment by winterlude** [comment]
The only variable that both my source code and the NLog config file must be aware of is `currentDataTransfer`, because the `logDir` is used only inside the NLog config file in order to simplify its structure and make it more readable/maintainable. Indeed, whoever want to use the application might define other variables, which I cannot foresee in my code. How can I replace all variables used in the `target.FileName` if I don't know them?!

Basically, I cannot do what you suggested, because my source code doesn't know how to compose the `target.FileName`, because this is usually decided by someone else - in the NLog config file.

I really believe that this should be fixed as follows. Every time the method `LogManager.ReconfigExistingLoggers()` is called, the NLog  plugin should loop through all variables that are in `LogManager.Configuration.Variables`, search their names into the original value of `target.FileName` and, in case, replace them with their current value.

**Comment by 304NotModified** [comment]
Too bad you can't workaround it. 

That `LogManager.ReconfigExistingLoggers();` is removing the new values of the variables, is a bug. We should unit test it, and fix it.

**Comment by 304NotModified** [comment]
Thanks for reporting. If you have the time to create an unit test, then that would really boost fixing the bug.

**Comment by Xharze** [comment]
Could you provide a sample project for this issue? I can't seem to reproduce this and the unit tests I've created works as expected, maintaining the changed variables after `LogManager.ReconfigureExistingLoggers()`

**Comment by winterlude** [comment]
I don't know which is the common way to share projects and/or files.
Anyway, I created this: https://gist.github.com/winterlude/caa743f6055806e3f21a
HTH

**Comment by 304NotModified** [comment]
I like the Gist. We will check/fix this for 4.1

**Comment by mr-unicoder** [comment]
Same case here, please fix it ASAP, i've fixed it now using custom layout renderer but it doesn't make sense to implement one for each variable.

**Comment by 304NotModified** [comment]
I have confirmed the bug in an unit test. (this is good news)

**Comment by 304NotModified** [comment]
Discussion continued at #790

**Comment by 304NotModified** [comment]
moved to should have as this is not just a quickfix, but needs more time.

**Comment by 304NotModified** [comment]
Fixed in 4.1

**Comment by Niklas-Peter** [comment]
> Fixed in 4.1

Really? In my test it is still not working or am I doing sth. wrong?
```
static void Main(string[] args)
{
    Console.WriteLine(TargetFromConfig().FileName); // Output: 'myvalue'

    LogManager.Configuration.Variables["myvar"] = "NEW_VALUE.log";
    LogManager.ReconfigExistingLoggers();

    // Output: 'myvalue', should be: 'NEW_VALUE.log'
    Console.WriteLine(TargetFromConfig().FileName); 
}

public static FileTarget TargetFromConfig()
{
    return (FileTarget)LogManager.Configuration.AllTargets[0];
}
```

**Comment by 304NotModified** [comment]
Yes but you need the variable layout renderer. See http://nlog-project.org/2015/08/31/nlog-4-1-0-is-now-available.html 

No need for `ReconfigExistingLoggers`

**Comment by leobuskin** [comment]
Guys, something wrong w/ ReconfigExistingLoggers(), really. It doesn't update any logger after runtime configuration. Test: https://gist.github.com/leobuskin/d70d16a567cd9a0add451a494ee81943
